import {Chess} from '../../chess.js';import {uci} from './E020-concepts.mjs';
import {explainMove as parent,priority as parentPriority} from './E033-traps.mjs';
const all=c=>c.board().flat().filter(Boolean),shade=s=>(s.charCodeAt(0)-97+ +s[1]-1)%2;
export function diagonals(square){const x=square.charCodeAt(0)-97,y=+square[1]-1;return[1,-1].map(slope=>{const line=[];for(let f=0;f<8;f++){const rank=y+(f-x)*slope;if(rank>=0&&rank<8)line.push(String.fromCharCode(97+f)+(rank+1));}return line;});}
export function scope(c,b){const x=b.square.charCodeAt(0)-97,y=+b.square[1],squares=[];for(const dx of [-1,1])for(const dy of [-1,1])for(let i=1;i<8;i++){const f=x+i*dx,r=y+i*dy;if(f<0||f>7||r<1||r>8)break;const s=String.fromCharCode(97+f)+r;squares.push(s);if(c.get(s))break;}return squares.sort();}
export function pattern(c,b){const pawns=all(c).filter(p=>p.type==='p'&&p.color===b.color),color=shade(b.square),dir=b.color==='w'?1:-1,opposite=pawns.filter(p=>shade(p.square)!==color).map(p=>p.square).sort();
 if(pawns.length>=2&&opposite.length===pawns.length)return{kind:'good',pawns:opposite,colorComplex:color};
 const fixed=pawns.filter(p=>p.square[0]>='c'&&p.square[0]<='f'&&shade(p.square)===color&&c.get(p.square[0]+(+p.square[1]+dir))?.type==='p'&&c.get(p.square[0]+(+p.square[1]+dir)).color!==b.color).map(p=>({square:p.square,blocker:p.square[0]+(+p.square[1]+dir)})).sort((a,b)=>a.square.localeCompare(b.square));
 const blockers=fixed.filter(p=>Math.abs(p.square.charCodeAt(0)-b.square.charCodeAt(0))===1&&+p.square[1]===+b.square[1]+dir).map(p=>p.square),controlled=scope(c,b);if(fixed.length>=2&&blockers.length&&controlled.length<=4)return{kind:'bad',pawns:pawns.map(p=>p.square).sort(),fixed,blockers,controlled,colorComplex:color};return null;
}
export function flank(c,b){const rank=b.color==='w'?2:7;if(!['b','g'].includes(b.square[0])||+b.square[1]!==rank)return null;const dir=b.color==='w'?1:-1,pawn=[rank+dir,rank+2*dir].map(r=>b.square[0]+r).find(s=>c.get(s)?.type==='p'&&c.get(s).color===b.color);return pawn?{bishop:b.square,pawn,wing:b.square[0]==='g'?'kingside':'queenside'}:null;}
export function priority(e){return({'prepared-fianchetto':98,'double-fianchetto':99,'open-bishop-diagonal':96,'opened-bishop-diagonal':97,'bishop-color-pattern':96.4}[e.id]??parentPriority(e));}
export function selectComment(events){return [...events].sort((a,b)=>priority(b)-priority(a))[0]?.text||null;}
export function explainMove(input){const base=parent(input),before=new Chess(input.fen),after=new Chess(input.fen),played=after.move(input.move),extra=[],bishops=all(after).filter(p=>p.type==='b'&&p.color===played.color);if(after.isGameOver())return base;const add=(id,text,evidence)=>extra.push({id,text,evidence:{...evidence,afterFen:after.fen()},qualityClaim:false});
 for(const b of bishops){const moved=played.piece==='b'&&b.square===played.to;
  if(moved){const home=b.color==='w'?(b.square[0]==='b'?'c1':'f1'):(b.square[0]==='b'?'c8':'f8'),f=flank(after,b);if(f&&played.from===home){add('prepared-fianchetto',`Fianchetto formation: bishop ${b.square} sits behind your advanced ${f.pawn[0]}-pawn.`,{bishop:b.square,home,...f,played:uci(played)});const flanks=bishops.map(p=>flank(after,p)).filter(Boolean);if(new Set(flanks.map(f=>f.wing)).size===2)add('double-fianchetto','Double fianchetto: both bishops sit behind advanced flank pawns.',{bishops:flanks,played:uci(played)});}}
  for(const line of diagonals(b.square)){if(line.length<5||line.some(s=>s!==b.square&&after.get(s)))continue;const prior=before.get(b.square)?.type==='b'&&before.get(b.square)?.color===b.color,blockers=line.filter(s=>s!==b.square&&before.get(s)),changed=moved||prior&&blockers.length;if(!changed)continue;const evidence={bishop:b.square,line,controlled:line.filter(s=>s!==b.square),long:line.length===8,played:uci(played)};add('open-bishop-diagonal',`Open ${evidence.long?'long ':''}diagonal: bishop ${b.square} controls ${line[0]}–${line.at(-1)}.`,evidence);if(!moved&&prior&&blockers.length)add('opened-bishop-diagonal',`Your move opens bishop ${b.square}’s ${line[0]}–${line.at(-1)} diagonal.`,{...evidence,beforeFen:before.fen(),blockers});}
  if(moved||played.piece==='p'){const p=pattern(after,b),prior=before.get(b.square)?.type==='b'?pattern(before,{...b}):null;if(p&&(moved||JSON.stringify(p)!==JSON.stringify(prior)))add('bishop-color-pattern',p.kind==='good'?`Good-bishop pattern: your own pawns occupy the opposite color to bishop ${b.square}.`:`Bad-bishop pattern: fixed own pawns block bishop ${b.square}’s scope.`,{bishop:b.square,played:uci(played),pattern:p});}
 }
 if(!extra.length)return base;const events=[...base.events,...extra],comment=selectComment(events);if(comment&&comment.split(/\s+/).length>24)throw Error('Comment exceeds 24 words');return{...base,schema:'coach-concepts-v15',events,comment};}
