import {Chess} from '../../chess.js';import {uci,VALUES} from './E020-concepts.mjs';import {pawnFeatures} from './E021-features.mjs';import {validateHistory} from './E024-transitions.mjs';import {explainMove as parent,priority as previous} from './E036-passers.mjs';
const all=c=>c.board().flat().filter(Boolean),balance=(c,color)=>all(c).reduce((n,p)=>n+VALUES[p.type]*(p.color===color?1:-1),0),distance=(a,b)=>Math.max(Math.abs(a.charCodeAt(0)-b.charCodeAt(0)),Math.abs(+a[1]- +b[1]));
const bounded=(n,name,max)=>{if(!Number.isInteger(n)||n<0||n>max)throw Error(`Invalid ${name}`);return n;};
export function routeQuery(c,color,pawn,depth,budget){bounded(depth,'promotionDepth',6);bounded(budget.limit,'maxRouteNodes',50000);const rootFen=c.fen(),initialBalance=balance(c,color),tick=()=>{if(budget.nodes>=budget.limit)throw Error('route-budget');budget.nodes++;};
 const safe=target=>{tick();const fen=c.fen(),mate=c.isCheckmate(),responses=[];if(mate)return{kind:'safe-promotion',fen,target,mate:true,responses};if(c.isGameOver()||balance(c,color)<=initialBalance)return null;for(const m of c.moves({verbose:true})){tick();c.move(m);let good;try{const q=c.get(target),gain=balance(c,color)-initialBalance;good=!c.isGameOver()&&q?.type==='q'&&q.color===color&&gain>0;responses.push({move:uci(m),gain,fen:c.fen()});}finally{c.undo();}if(!good)return null;}return{kind:'safe-promotion',fen,target,mate:false,responses};};
 const walk=(square,left)=>{tick();if(c.isGameOver()||!left||c.get(square)?.type!=='p'||c.get(square)?.color!==color)return null;const fen=c.fen(),moves=c.moves({verbose:true});if(c.turn()===color){for(const m of moves.filter(m=>m.from===square&&m.to[0]===square[0]&&(!m.promotion||m.promotion==='q'))){c.move(m);let child;try{child=m.promotion?safe(m.to):walk(m.to,left-1);}finally{c.undo();}if(child)return{kind:'choice',fen,move:uci(m),child};}return null;}const branches=[];for(const m of moves){c.move(m);let child;try{child=walk(square,left);}finally{c.undo();}if(!child)return null;branches.push({move:uci(m),child});}return branches.length?{kind:'all',fen,branches}:null;};
 const tree=walk(pawn,depth);return{rootFen,color,pawn,depth,initialBalance,win:!!tree,tree};}
export function squareGate(c,pawn,color){const pieces=all(c),p=c.get(pawn);if(p?.type!=='p'||p.color!==color||pieces.length!==3||pieces.filter(p=>p.type==='k').length!==2||+pawn[1]===(color==='w'?2:7))return null;const promotion=pawn[0]+(color==='w'?8:1),pushes=Math.abs(+promotion[1]- +pawn[1]),king=pieces.find(p=>p.type==='k'&&p.color!==color).square,d=distance(king,promotion),tempoAllowance=c.turn()===color?0:1;return d>pushes+tempoAllowance?{pawn,promotion,king,pushes,kingDistance:d,tempoAllowance}:null;}
export function priority(e){return({'promotion-route':156.5,'rule-of-square':156.6}[e.id]??previous(e));}export function selectComment(events){return [...events].sort((a,b)=>priority(b)-priority(a))[0]?.text||null;}
export function explainMove(input){const base=parent(input),depth=bounded(input.promotionDepth??0,'promotionDepth',6),limit=bounded(input.maxRouteNodes??50000,'maxRouteNodes',50000);if(!depth)return base;const h=validateHistory(input),c=new Chess(h?.start||input.fen);if(h)for(const m of h.moves)c.move(m);const played=c.move(input.move),color=played.color,budget={limit,nodes:0},queries=[],extra=[];if(c.isGameOver())return base;let status='complete';const candidates=pawnFeatures(c,color).passed.filter(s=>played.piece==='k'||played.piece==='p'&&s===played.to);
 try{for(const pawn of candidates){const proof=routeQuery(c,color,pawn,depth,budget);queries.push({pawn,win:proof.win});if(!proof.win)continue;const evidence={pawn,played:uci(played),afterFen:c.fen(),proof};extra.push({id:'promotion-route',text:`Passed-pawn route: ${pawn} can queen within ${depth} pushes against every reply, surviving the next response.`,evidence,qualityClaim:false});const square=squareGate(c,pawn,color);if(square)extra.push({id:'rule-of-square',text:`Rule of the square: the king cannot catch pawn ${pawn}’s verified promotion route.`,evidence:{...evidence,square},qualityClaim:false});}}
 catch(e){if(e.message!=='route-budget')throw e;status='exhausted';extra.length=0;}
 const events=[...base.events,...extra],comment=selectComment(events);if(comment?.split(/\s+/).length>24)throw Error('Comment exceeds 24 words');return{...base,schema:'coach-concepts-v18',events,comment,routeAnalysis:{depth,limit,nodes:budget.nodes,status,queries}};}
