import {Chess} from '../../chess.js';import {VALUES,uci} from './E020-concepts.mjs';import {explainMove as parent,priority as previous} from './E041-defense.mjs';
const balance=(c,color)=>c.board().flat().filter(Boolean).reduce((n,p)=>n+VALUES[p.type]*(p.color===color?1:-1),0);
export const priority=e=>e.id==='defensive-counterattack'?179.1:previous(e);
export function explainMove(input){const enabled=input.defensiveTags??false,limit=input.maxDefensiveTagNodes??50000;if(typeof enabled!=='boolean')throw Error('defensiveTags must be boolean');if(!Number.isInteger(limit)||limit<0||limit>50000)throw Error('maxDefensiveTagNodes must be an integer from 0 to 50000');const base=parent(input);if(!enabled)return base;const defense=base.events.find(e=>e.id==='unique-mate-defense');if(!defense)return base;
 const c=new Chess(input.history?.fen||input.fen);if(input.history)for(const m of input.history.moves)c.move(m);const initialBalance=balance(c,c.turn()),played=c.move(input.move),color=played.color,unit={square:played.to,...c.get(played.to)};if(!c.isCheck()||c.isGameOver())return base;const offers=[],budget={nodes:0,tick(){if(++this.nodes>limit)throw Error('defensive-tag-budget');}};let status='complete',extra=[];
 try{budget.tick();if(played.piece!=='k'&&VALUES[played.piece]>VALUES[played.captured||'k'])for(const m of c.moves({verbose:true})){budget.tick();const capturedSquare=m.flags.includes('e')?m.to[0]+(m.color==='w'?'5':'4'):m.to;if(!m.captured||capturedSquare!==played.to)continue;c.move(m);let witness=null;try{const gain=balance(c,color)-initialBalance;if(c.isGameOver()||gain>=0)continue;const afterFen=c.fen(),responses=[];let good=true;for(const reply of c.moves({verbose:true})){budget.tick();c.move(reply);try{const delta=balance(c,color)-initialBalance;if(c.isGameOver()||delta>=0){good=false;break;}responses.push({move:uci(reply),gain:delta,fen:c.fen()});}finally{c.undo();}}if(good&&responses.length)witness={move:uci(m),afterFen,gain,responses};}finally{c.undo();}if(witness)offers.push(witness);}
  const sacrifice=offers.length>0,label=sacrifice?'Defensive sacrifice offer':'Counterattack';extra=[{id:'defensive-counterattack',text:sacrifice?`${label}: ${played.san} is your only move avoiding mate in one.`:`${label}: ${played.san} checks and is your only move avoiding mate in one.`,qualityClaim:false,evidence:{played:uci(played),afterFen:c.fen(),unit,initialBalance,defenseProof:defense.evidence,offers,conditionalAcceptance:sacrifice}}];
 }catch(error){if(error.message!=='defensive-tag-budget')throw error;status='exhausted';extra=[];}
 const events=[...base.events,...extra],comment=[...events].sort((a,b)=>priority(b)-priority(a))[0]?.text||null;if(comment&&comment.split(/\s+/).length>24)throw Error('Comment exceeds 24 words');return{...base,schema:'coach-concepts-v23',events,comment,defensiveTagAnalysis:{limit,nodes:budget.nodes,status}};
}
