import {Chess} from '../../chess.js';import {uci} from './E020-concepts.mjs';import {explainMove as parent,priority as previous} from './E045-supported.mjs';
const board=f=>{const c=new Chess(f.history?.fen||f.fen);if(f.history)for(const m of f.history.moves)c.move(m);return c;},xy=s=>[s.charCodeAt(0)-97,+s[1]-1],around=s=>[-1,0,1].flatMap(dx=>[-1,0,1].filter(dy=>dx||dy).map(dy=>{const [x,y]=xy(s);return x+dx>=0&&x+dx<8&&y+dy>=0&&y+dy<8?String.fromCharCode(97+x+dx)+(y+dy+1):null;})).filter(Boolean),edge=s=>'ah'.includes(s[0])||'18'.includes(s[1]),near=(a,b)=>Math.max(...xy(a).map((n,i)=>Math.abs(n-xy(b)[i])))===1,parity=s=>xy(s).reduce((a,b)=>a+b,0)%2;
export const netIds=new Set(['greco-mate','blackburne-mate','kill-box-mate']);export const priority=e=>netIds.has(e.id)?196.2:previous(e);
export function explainMove(input){const enabled=input.netPatternTags??false,limit=input.maxNetPatternNodes??50000;if(typeof enabled!=='boolean')throw Error('netPatternTags must be boolean');if(!Number.isInteger(limit)||limit<0||limit>50000)throw Error('maxNetPatternNodes must be an integer from 0 to 50000');const base=parent(input);if(!enabled)return base;const c=board(input),move=c.move(input.move);if(!c.isCheckmate())return base;let nodes=0,status='complete';const tick=()=>{if(++nodes>limit)throw Error('net-pattern-budget');},extra=[],color=move.color,enemy=c.turn(),king=c.board().flat().find(p=>p?.type==='k'&&p.color===enemy).square,checker={square:move.to,...c.get(move.to)},checkers=c.attackers(king,color),flight=new Chess(c.fen());flight.remove(king);const all=c.board().flat().filter(p=>p?.color===color),vacant=around(king).filter(s=>!c.get(s)),attack=(s,p)=>flight.attackers(s,color).includes(p.square),add=(id,text,e)=>{if(!extra.some(x=>x.id===id))extra.push({id,text,qualityClaim:false,evidence:{after:c.fen(),played:uci(move),king,color,checker,...e}});};
 try{tick();if(checkers.length===1&&checkers[0]===move.to){if('ah'.includes(king[0])&&'18'.includes(king[1])&&['r','q'].includes(checker.type)&&move.to[0]===king[0]){const file=king[0]==='h'?'g':'b',escape=file+king[1],blocker=file+(king[1]==='8'?'7':'2');if(!c.get(escape)&&c.get(blocker)?.color===enemy&&c.get(blocker)?.type==='p'&&!attack(escape,checker))for(const bishop of all.filter(p=>p.type==='b')){tick();if(attack(escape,bishop))add('greco-mate',`Greco mate: ${checker.type==='r'?'rook':'queen'} ${move.to} checks; bishop ${bishop.square} seals ${escape}, and pawn ${blocker} blocks escape.`,{bishop,flights:[escape],blocker:{square:blocker,...c.get(blocker)}});}}
 if(edge(king)&&checker.type==='b')for(const bishop of all.filter(p=>p.type==='b'&&p.square!==checker.square&&parity(p.square)!==parity(checker.square)))for(const knight of all.filter(p=>p.type==='n')){tick();const support=c.attackers(checker.square,color).includes(knight.square),bishopFlights=vacant.filter(s=>attack(s,bishop)&&!attack(s,checker)&&!attack(s,knight)),knightFlights=vacant.filter(s=>attack(s,knight)&&!attack(s,checker)&&!attack(s,bishop));if(bishopFlights.length&&knightFlights.length&&(!near(checker.square,king)||support))add('blackburne-mate',`Blackburne’s mate: bishops ${checker.square} and ${bishop.square} close diagonals; knight ${knight.square} seals ${knightFlights[0]}.`,{bishop,knight,support,bishopFlights,knightFlights,blockers:around(king).filter(s=>c.get(s)?.color===enemy).map(s=>({square:s,...c.get(s)}))});}
 if(edge(king)&&checker.type==='r'&&xy(king).reduce((n,v,i)=>n+Math.abs(v-xy(checker.square)[i]),0)===1)for(const queen of all.filter(p=>p.type==='q')){tick();const q=xy(queen.square),r=xy(checker.square),k=xy(king);if(q.some((v,i)=>Math.abs(v-r[i])!==2))continue;const between=String.fromCharCode(97+(q[0]+r[0])/2)+((q[1]+r[1])/2+1),box={min:q.map((v,i)=>Math.min(v,r[i])),max:q.map((v,i)=>Math.max(v,r[i]))},queenFlights=vacant.filter(s=>!attack(s,checker));if(!c.get(between)&&c.attackers(checker.square,color).includes(queen.square)&&k.every((v,i)=>v>=box.min[i]&&v<=box.max[i])&&queenFlights.length&&queenFlights.every(s=>attack(s,queen)))add('kill-box-mate',`Kill box mate: queen ${queen.square} protects rook ${checker.square}; together they close the king’s three-by-three box.`,{queen,between,box,queenFlights});}
 }}catch(error){if(error.message!=='net-pattern-budget')throw error;extra.length=0;status='exhausted';}const events=[...base.events,...extra],comment=[...events].sort((a,b)=>priority(b)-priority(a))[0]?.text||null;if(comment&&comment.split(/\s+/).length>24)throw Error('Comment exceeds 24 words');return{...base,schema:'coach-concepts-v27',events,comment,netPatternAnalysis:{limit,nodes,status}};
}
