import {Chess} from '../../chess.js';import {explainMove as parent,priority as prior} from './E062-space.mjs';
const code=m=>m.from+m.to+(m.promotion||'');
function record(c,uci){const before=c.fen(),m=c.move(uci);return{move:code(m),san:m.san,from:m.from,to:m.to,piece:m.piece,color:m.color,captured:m.captured||null,promotion:m.promotion||null,before,after:c.fen()};}
const pawn=(c,s,color)=>c.get(s)?.type==='p'&&c.get(s).color===color;
export const priority=e=>e.id==='pawn-storm'?101.05:prior(e);
export function explainMove(input){const enabled=input.pawnStormTags??false,limit=input.maxPawnStormNodes??50000;if(typeof enabled!=='boolean')throw Error('pawnStormTags must be boolean');if(!Number.isInteger(limit)||limit<0||limit>50000)throw Error('maxPawnStormNodes must be an integer from 0 to 50000');const base=parent(input);if(!enabled)return base;let nodes=0,status='complete';const extra=[],tick=()=>{if(++nodes>limit)throw Error('pawn-storm-budget');};
 try{tick();const c=new Chess(input.history?.fen||input.fen),history=[];if(input.history)for(const m of input.history.moves){tick();history.push(record(c,m));}if(!c.isGameOver()){const beforeFen=c.fen(),before=new Chess(beforeFen),played=record(c,input.move),enemy=played.color==='w'?'b':'w',castleIndex=history.findLastIndex(m=>m.color===enemy&&m.piece==='k'),priorIndex=history.findLastIndex(m=>m.color===played.color),castle=history[castleIndex],first=history[priorIndex];
  if(!c.isGameOver()&&played.piece==='p'&&!played.promotion&&castle&&first&&first.piece==='p'&&!first.promotion&&castleIndex<priorIndex&&priorIndex===history.length-2){tick();const rank=enemy==='w'?'1':'8',side=castle.to[0]==='g'?'k':castle.to[0]==='c'?'q':null,files=side==='k'?'fgh':'abc',king=c.board().flat().find(p=>p?.type==='k'&&p.color===enemy),relative=s=>played.color==='w'?+s[1]:9-+s[1],distance=s=>Math.abs(+king.square[1]-+s[1]);
   if(side&&castle.from==='e'+rank&&castle.to===(side==='k'?'g':'c')+rank&&castle.san.replace(/[+#]$/,'')===(side==='k'?'O-O':'O-O-O')&&king.square===castle.to&&first.to!==played.from&&pawn(before,first.to,played.color)&&pawn(c,first.to,played.color)&&[first.from,first.to,played.from,played.to].every(s=>files.includes(s[0]))&&[first,played].every(m=>relative(m.to)>relative(m.from)&&distance(m.to)<distance(m.from))&&[first.to,played.to].every(s=>relative(s)>=4&&distance(s)>0)&&Math.abs(first.to.charCodeAt(0)-played.to.charCodeAt(0))===1&&Math.abs(+first.to[1]-+played.to[1])<=1){
    const pawns=[first.to,played.to].map(square=>({square,type:'p',color:played.color})),responses=[];for(const m of c.moves({verbose:true})){tick();const child=new Chess(c.fen()),reply=record(child,code(m));responses.push({reply,terminal:child.isGameOver(),pawnPresent:pawns.map(p=>pawn(child,p.square,p.color))});}
    const text=`Pawn storm: ${first.san} and ${played.san} advanced distinct pawns toward their castled king on ${king.square}; both now occupy that flank.`;extra.push({id:'pawn-storm',qualityClaim:false,text,evidence:{beforeFen,afterFen:c.fen(),history,played,castleIndex,priorIndex,castle,priorAdvance:first,king:{square:king.square,type:'k',color:enemy},side,pawns,connection:{fileGap:1,rankGap:Math.abs(+first.to[1]-+played.to[1])},distances:[first,played].map(m=>({from:distance(m.from),to:distance(m.to)})),responses}});
   }
  }
 }}catch(error){if(error.message!=='pawn-storm-budget')throw error;extra.length=0;status='exhausted';}
 const events=[...base.events,...extra],comment=[...events].sort((a,b)=>priority(b)-priority(a))[0]?.text||null;if(comment&&comment.split(/\s+/).length>24)throw Error('Comment exceeds 24 words');return{...base,schema:'coach-concepts-v44',events,comment,pawnStormAnalysis:{limit,nodes,status}};
}
