import {Chess} from '../../chess.js';import {explainMove as parent,priority as prior} from './E065-triangle.mjs';
const code=m=>m.from+m.to+(m.promotion||'');
function record(c,move){const before=c.fen(),m=c.move(move);return{move:code(m),san:m.san,from:m.from,to:m.to,piece:m.piece,color:m.color,captured:m.captured||null,promotion:m.promotion||null,before,after:c.fen()};}
const identities=c=>c.board().flat().filter(Boolean).map(p=>({square:p.square,type:p.type,color:p.color})).sort((a,b)=>a.square.localeCompare(b.square));
const relative=(s,color)=>color==='w'?+s[1]:9-+s[1];
const passed=(p,rival)=>Math.abs(p.square.charCodeAt(0)-rival.square.charCodeAt(0))>1||relative(rival.square,p.color)<relative(p.square,p.color);
export const priority=e=>e.id==='pawn-race'?157.05:prior(e);
function query(c,color,square,depth,tick){const walk=(square,left)=>{tick();const fen=c.fen();if(c.get(square)?.type!=='p'||c.get(square)?.color!==color)return{kind:'captured',win:false,fen,square,left};if(c.isGameOver())return{kind:'terminal',win:false,fen,square,left};if(!left)return{kind:'limit',win:false,fen,square,left};const legal=c.moves({verbose:true});if(c.turn()!==color){const branches=[];for(const m of legal){tick();const move=record(c,code(m));let child;try{child=m.promotion?{kind:'rival-promoted',win:false,fen:c.fen(),promotion:m.promotion}:walk(square,left-1);}finally{c.undo();}branches.push({move,child});}return{kind:'all',fen,square,left,win:branches.length>0&&branches.every(b=>b.child.win),branches};}
 const advance=legal.filter(m=>m.from===square&&m.piece==='p'&&!m.captured&&m.to[0]===m.from[0]&&(!m.promotion||m.promotion==='q'));if(!advance.length)return{kind:'no-legal-push',win:false,fen,square,left};if(advance.length!==1)throw Error('Advanced race pawn has multiple straight queen choices');tick();const move=record(c,code(advance[0]));let child;try{if(move.promotion){const terminal=c.isGameOver(),continuations=[];if(!terminal)for(const reply of c.moves({verbose:true})){tick();const next=record(c,code(reply));continuations.push({reply:next,terminal:c.isGameOver(),queenPresent:c.get(move.to)?.type==='q'&&c.get(move.to)?.color===color});c.undo();}child={kind:'first',win:true,fen:c.fen(),square:move.to,terminal,continuations};}else child=walk(move.to,left-1);}finally{c.undo();}return{kind:'push',fen,square,left,win:child.win,move,child};};return walk(square,depth);}
export function explainMove(input){const enabled=input.pawnRaceTags??false,depth=input.pawnRaceDepth??6,limit=input.maxPawnRaceNodes??50000;if(typeof enabled!=='boolean')throw Error('pawnRaceTags must be boolean');if(!Number.isInteger(depth)||depth<0||depth>6)throw Error('pawnRaceDepth must be an integer from 0 to 6');if(!Number.isInteger(limit)||limit<0||limit>50000)throw Error('maxPawnRaceNodes must be an integer from 0 to 50000');const base=parent(input);if(!enabled)return base;let nodes=0,status='ineligible',refutationTree=null;const extra=[],tick=()=>{if(++nodes>limit)throw Error('pawn-race-budget');};
 try{tick();const c=new Chess(input.history?.fen||input.fen),history=[];if(input.history)for(const move of input.history.moves){tick();history.push(record(c,move));}if(!c.isGameOver()){const beforeFen=c.fen(),played=record(c,input.move),pieces=identities(c),pawns=pieces.filter(p=>p.type==='p'),pawn=pawns.find(p=>p.color===played.color),rival=pawns.find(p=>p.color!==played.color);if(!c.isGameOver()&&played.piece==='p'&&!played.captured&&!played.promotion&&pieces.length===4&&pieces.filter(p=>p.type==='k').length===2&&pawns.length===2&&pawn&&rival&&pawn.square===played.to&&[pawn,rival].every(p=>relative(p.square,p.color)>=5)&&passed(pawn,rival)&&passed(rival,pawn)){const pushes=8-relative(pawn.square,pawn.color);if(depth<2*pushes)status='short-profile';else{const tree=query(c,played.color,pawn.square,depth,tick);status=tree.win?'proven':'refuted';if(tree.win){const text=`Pawn race: ${pawn.square} can queen before ${rival.square} against every legal defense, using ${pushes} pawn ${pushes===1?'move':'moves'}.`;extra.push({id:'pawn-race',qualityClaim:false,text,evidence:{beforeFen,afterFen:c.fen(),history,played,pieces,pawn,rival,passed:{own:true,rival:true},pushes,depth,tree}});}else refutationTree=tree;}}}
 }catch(error){if(error.message!=='pawn-race-budget')throw error;extra.length=0;refutationTree=null;status='exhausted';}
 const events=[...base.events,...extra],comment=[...events].sort((a,b)=>priority(b)-priority(a))[0]?.text||null;if(comment&&comment.split(/\s+/).length>24)throw Error('Comment exceeds 24 words');return{...base,schema:'coach-concepts-v47',events,comment,pawnRaceAnalysis:{limit,nodes,depth,status,refutationTree}};
}
