import {Chess} from '../../chess.js';import {explainMove as parent,priority as prior} from './E070-outpost.mjs';
const values={p:1,n:3,b:3,r:5,q:9,k:0},uci=m=>m.from+m.to+(m.promotion||'');
function play(c,move){const before=c.fen(),m=c.move(move);return{move:uci(m),san:m.san,from:m.from,to:m.to,piece:m.piece,color:m.color,captured:m.captured||null,promotion:m.promotion||null,before,after:c.fen()};}
const flags=c=>({check:c.isCheck(),checkmate:c.isCheckmate(),stalemate:c.isStalemate(),draw:c.isDraw(),gameOver:c.isGameOver()});
const balance=(c,color)=>c.board().flat().filter(Boolean).reduce((n,p)=>n+values[p.type]*(p.color===color?1:-1),0);
function squares(s){return[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]].map(([df,dr])=>String.fromCharCode(s.charCodeAt(0)+df)+(Number(s[1])+dr)).filter(x=>/^[a-h][1-8]$/.test(x)).sort();}
const forceIds=new Set(['fork','broad-fork','triple-attack','discovered-double-attack']);
function terminalGuard(input,base){if(!input.history)return{base,guard:null};const c=new Chess(input.history.fen),history=input.history.moves.map(move=>play(c,move)),played=play(c,input.move),replies=[];for(const move of c.moves({verbose:true})){const reply=play(c,uci(move));replies.push({reply,...flags(c)});c.undo();}const terminal=replies.some(r=>r.gameOver),suppressedIds=terminal?[...new Set(base.events.filter(e=>forceIds.has(e.id)).map(e=>e.id))].sort():[],events=terminal?base.events.filter(e=>!forceIds.has(e.id)):base.events,comment=[...events].sort((a,b)=>prior(b)-prior(a))[0]?.text||null;return{base:{...base,events,comment},guard:{history,played,replies,terminal,suppressedIds,nodes:history.length+1+replies.length}};}
export const priority=e=>e.id==='octopus-knight'?145.05:prior(e);
export function explainMove(input){const enabled=input.octopusTags??false,limit=input.maxOctopusNodes??50000;if(typeof enabled!=='boolean')throw Error('octopusTags must be boolean');if(!Number.isInteger(limit)||limit<0||limit>50000)throw Error('maxOctopusNodes must be an integer from 0 to 50000');let base=parent(input);if(!enabled)return base;const guarded=terminalGuard(input,base);base=guarded.base;let nodes=0,status='ineligible',refutation=null;const extra=[],tick=()=>{if(++nodes>limit)throw Error('octopus-budget');};
 try{tick();const outpost=base.events.find(e=>e.id==='advanced-knight-outpost');if(outpost){const c=new Chess(input.history?.fen||input.fen),history=[];if(input.history)for(const move of input.history.moves){tick();history.push(play(c,move));}const played=play(c,input.move);tick();const attacks=squares(played.to),king=c.board().flat().find(p=>p?.type==='k'&&p.color!==played.color)?.square,queens=c.board().flat().filter(p=>p?.type==='q'&&p.color!==played.color&&attacks.includes(p.square)).map(p=>p.square).sort();if(['d','e'].includes(played.to[0])&&attacks.length===8&&king&&attacks.includes(king)&&queens.length&&c.isCheck()&&!c.isGameOver()){const baseline=balance(c,played.color),defenses=[];for(const move of c.moves({verbose:true})){tick();const reply=play(c,uci(move)),terminal=flags(c),captures=[];if(!terminal.gameOver)for(const m of c.moves({verbose:true}).filter(m=>m.from===played.to&&m.piece==='n'&&m.captured==='q'&&queens.includes(m.to))){tick();const capture=play(c,uci(m)),state=flags(c),gain=balance(c,played.color)-baseline,counters=[];if(!state.gameOver)for(const counter of c.moves({verbose:true})){tick();const response=play(c,uci(counter));counters.push({response,...flags(c),gain:balance(c,played.color)-baseline});c.undo();}const win=gain>0&&!state.draw&&!state.stalemate&&(state.checkmate||(!state.gameOver&&counters.every(r=>r.gain>0&&!r.draw&&!r.checkmate&&!r.gameOver)));captures.push({capture,...state,gain,counters,win});c.undo();}defenses.push({reply,...terminal,captures,win:!terminal.gameOver&&captures.some(x=>x.win)});c.undo();}const proof={values:{...values},baseline,defenses,win:defenses.length>0&&defenses.every(d=>d.win)};if(proof.win){status='proven';extra.push({id:'octopus-knight',qualityClaim:false,text:`Octopus knight: ${played.san} controls eight squares with pawn support; every legal defense permits a queen capture with immediate material gain.`,evidence:{history,played,attacks,king,queens,outpost,proof}});}else{status='queen-gain-refuted';refutation={history,played,attacks,king,queens,outpost,proof};}}}
 }catch(error){if(error.message!=='octopus-budget')throw error;extra.length=0;refutation=null;status='exhausted';}
 const events=[...base.events,...extra],comment=[...events].sort((a,b)=>priority(b)-priority(a))[0]?.text||null;if(comment&&comment.split(/\s+/).length>24)throw Error('Comment exceeds 24 words');return{...base,schema:'coach-concepts-v52',events,comment,terminalDefenseGuard:guarded.guard,octopusAnalysis:{limit,nodes,status,refutation}};
}
