// flags.js — maps a Chess.com country token to a bundled flag asset in flags/.
//
// Chess.com never prints the country name on the board; it renders only a CSS class on the
// player block — and it uses TWO different shapes depending on the surface:
//   archive / history pages:  <div class="cc-country-flag-component country-2 ...">   // numeric id
//   live game pages:          <div class="cc-country-flag-component country-us ...">  // ISO/pseudo code
// content.js scrapes whichever token follows `country-`; these tables turn it into the basename of
// the matching Kenney flag SVG (flags/<code>.svg). Both the id->ISO pairing and the code list come
// from flag_map.csv (Chess.com only exposes the opaque ids on archive pages), and the maps below are
// generated from it. Numeric tokens hit the *_ID_* tables, alpha tokens hit the *_CODE_* tables.
//
// Codes are ISO 3166-1 alpha-2 as used by the Kenney pack, plus a few extras the pack ships:
// GB_ENG / GB_SCT / GB_WLS for England / Scotland / Wales, and UN for "International".
// Countries Chess.com supports but the pack has no art for are intentionally omitted — they
// resolve to null and the avatar falls back to the username initial (see analysis.js).
//
// Flags are CC0 (Kenney.nl) — see ATTRIBUTIONS.md. To regenerate after Chess.com adds ids,
// rebuild this table from flag_map.csv.
export const COUNTRY_ID_TO_FLAG = {
  "2": "US",
  "3": "CA",
  "4": "AR",
  "5": "BE",
  "9": "AF",
  "10": "AL",
  "11": "AD",
  "12": "AI",
  "13": "AG",
  "14": "AM",
  "15": "AW",
  "17": "AU",
  "18": "AT",
  "19": "BS",
  "20": "BH",
  "21": "BB",
  "22": "BY",
  "23": "BZ",
  "24": "BM",
  "25": "BO",
  "26": "BA",
  "27": "BR",
  "28": "BG",
  "30": "KY",
  "32": "CL",
  "33": "CN",
  "34": "CO",
  "35": "CR",
  "36": "HR",
  "37": "CU",
  "38": "CW",
  "39": "CY",
  "40": "CZ",
  "41": "DK",
  "42": "DM",
  "43": "DO",
  "44": "EC",
  "45": "EG",
  "46": "SV",
  "47": "EE",
  "49": "FO",
  "50": "FJ",
  "51": "FI",
  "52": "FR",
  "53": "GE",
  "54": "DE",
  "55": "GI",
  "56": "GR",
  "57": "GL",
  "58": "GD",
  "60": "GU",
  "61": "GT",
  "63": "GY",
  "64": "HT",
  "65": "HN",
  "66": "HK",
  "67": "HU",
  "68": "IS",
  "69": "IN",
  "70": "ID",
  "71": "IR",
  "72": "IQ",
  "73": "IE",
  "74": "IM",
  "75": "IL",
  "76": "IT",
  "77": "JM",
  "78": "JP",
  "80": "JO",
  "81": "KZ",
  "82": "KI",
  "84": "KW",
  "85": "LV",
  "86": "LB",
  "87": "LI",
  "88": "LT",
  "89": "LU",
  "90": "MO",
  "91": "MK",
  "92": "MY",
  "93": "MT",
  "95": "MX",
  "96": "MD",
  "97": "MC",
  "98": "MS",
  "99": "NR",
  "100": "NP",
  "101": "NL",
  "102": "NZ",
  "103": "NI",
  "104": "NO",
  "105": "OM",
  "106": "PK",
  "107": "PA",
  "108": "PG",
  "109": "PY",
  "110": "PE",
  "111": "PH",
  "112": "PL",
  "113": "PT",
  "114": "PR",
  "115": "RO",
  "116": "RU",
  "118": "KN",
  "119": "LC",
  "122": "SM",
  "123": "SA",
  "125": "SG",
  "126": "SK",
  "127": "SI",
  "128": "SB",
  "129": "ZA",
  "131": "SR",
  "132": "SE",
  "133": "CH",
  "134": "TW",
  "135": "TH",
  "136": "TO",
  "137": "TT",
  "138": "TR",
  "139": "TM",
  "140": "TV",
  "141": "UA",
  "142": "AE",
  "143": "UY",
  "145": "UZ",
  "146": "VU",
  "147": "VA",
  "148": "VE",
  "149": "VN",
  "151": "YE",
  "153": "AS",
  "154": "VC",
  "156": "AZ",
  "157": "MN",
  "158": "SY",
  "159": "GB_ENG",
  "160": "MH",
  "162": "GB_SCT",
  "163": "ES",
  "164": "GB",
  "166": "GB_WLS",
  "175": "KR",
  "176": "KG",
  "177": "BD",
  "178": "SD",
  "179": "BJ",
  "180": "BT",
  "181": "BW",
  "182": "BN",
  "183": "BI",
  "184": "KH",
  "185": "CM",
  "186": "CV",
  "187": "CF",
  "188": "TD",
  "189": "CG",
  "190": "CI",
  "191": "DJ",
  "192": "GQ",
  "193": "GA",
  "194": "GH",
  "195": "KE",
  "196": "LA",
  "197": "LR",
  "198": "MG",
  "199": "MA",
  "200": "MZ",
  "201": "MM",
  "202": "NA",
  "203": "NE",
  "204": "NG",
  "206": "QA",
  "207": "RW",
  "208": "WS",
  "209": "ST",
  "210": "SN",
  "211": "SL",
  "212": "SO",
  "213": "LK",
  "214": "SZ",
  "215": "TJ",
  "216": "TZ",
  "217": "TL",
  "218": "TG",
  "219": "TN",
  "220": "UG",
  "221": "ZM",
  "222": "ZW",
  "223": "DZ",
  "224": "MR",
  "225": "UN",
  "231": "RS",
  "241": "ME",
  "261": "LY",
  "271": "GM",
  "281": "MW",
  "291": "PS",
  "301": "ET",
  "311": "MU",
  "312": "LS",
  "313": "ML",
  "314": "MV",
  "318": "CD",
  "319": "AO",
  "320": "KM",
  "321": "ER",
  "322": "GN",
  "323": "GW",
  "324": "FM",
  "325": "KP",
  "326": "PW",
  "327": "SC",
  "328": "EH",
  "329": "VG",
  "330": "SS",
  "334": "BF",
  "339": "SX",
  "340": "TC",
  "350": "PF",
};

// Display names for the hover tooltip on each flag avatar. Same ids/source as the flag map above
// (flag_map.csv) — kept in lock-step so every flag we render also has a name to label it.
export const COUNTRY_ID_TO_NAME = {
  "2": "United States",
  "3": "Canada",
  "4": "Argentina",
  "5": "Belgium",
  "9": "Afghanistan",
  "10": "Albania",
  "11": "Andorra",
  "12": "Anguilla",
  "13": "Antigua/Barbuda",
  "14": "Armenia",
  "15": "Aruba",
  "17": "Australia",
  "18": "Austria",
  "19": "Bahamas",
  "20": "Bahrain",
  "21": "Barbados",
  "22": "Belarus",
  "23": "Belize",
  "24": "Bermuda",
  "25": "Bolivia",
  "26": "Bosnia-Herzegovina",
  "27": "Brazil",
  "28": "Bulgaria",
  "30": "Cayman Islands",
  "32": "Chile",
  "33": "China",
  "34": "Colombia",
  "35": "Costa Rica",
  "36": "Croatia",
  "37": "Cuba",
  "38": "Curacao",
  "39": "Cyprus",
  "40": "Czech Republic",
  "41": "Denmark",
  "42": "Dominica",
  "43": "Dominican Republic",
  "44": "Ecuador",
  "45": "Egypt",
  "46": "El Salvador",
  "47": "Estonia",
  "49": "Faroe Islands",
  "50": "Fiji",
  "51": "Finland",
  "52": "France",
  "53": "Georgia",
  "54": "Germany",
  "55": "Gibraltar",
  "56": "Greece",
  "57": "Greenland",
  "58": "Grenada",
  "60": "Guam",
  "61": "Guatemala",
  "63": "Guyana",
  "64": "Haiti",
  "65": "Honduras",
  "66": "Hong Kong",
  "67": "Hungary",
  "68": "Iceland",
  "69": "India",
  "70": "Indonesia",
  "71": "Iran",
  "72": "Iraq",
  "73": "Ireland",
  "74": "Isle of Man",
  "75": "Israel",
  "76": "Italy",
  "77": "Jamaica",
  "78": "Japan",
  "80": "Jordan",
  "81": "Kazakhstan",
  "82": "Kiribati",
  "84": "Kuwait",
  "85": "Latvia",
  "86": "Lebanon",
  "87": "Liechtenstein",
  "88": "Lithuania",
  "89": "Luxembourg",
  "90": "Macao",
  "91": "North Macedonia",
  "92": "Malaysia",
  "93": "Malta",
  "95": "Mexico",
  "96": "Moldova",
  "97": "Monaco",
  "98": "Montserrat",
  "99": "Nauru",
  "100": "Nepal",
  "101": "Netherlands",
  "102": "New Zealand",
  "103": "Nicaragua",
  "104": "Norway",
  "105": "Oman",
  "106": "Pakistan",
  "107": "Panama",
  "108": "Papua New Guinea",
  "109": "Paraguay",
  "110": "Peru",
  "111": "Philippines",
  "112": "Poland",
  "113": "Portugal",
  "114": "Puerto Rico",
  "115": "Romania",
  "116": "Russia",
  "118": "Saint Kitts/Nevis",
  "119": "Saint Lucia",
  "122": "San Marino",
  "123": "Saudi Arabia",
  "125": "Singapore",
  "126": "Slovakia",
  "127": "Slovenia",
  "128": "Solomon Islands",
  "129": "South Africa",
  "131": "Suriname",
  "132": "Sweden",
  "133": "Switzerland",
  "134": "Taiwan",
  "135": "Thailand",
  "136": "Tonga",
  "137": "Trinidad/Tobago",
  "138": "Türkiye",
  "139": "Turkmenistan",
  "140": "Tuvalu",
  "141": "Ukraine",
  "142": "United Arab Emirates",
  "143": "Uruguay",
  "145": "Uzbekistan",
  "146": "Vanuatu",
  "147": "Vatican City",
  "148": "Venezuela",
  "149": "Vietnam",
  "151": "Yemen",
  "153": "American Samoa",
  "154": "Saint Vincent and the Grenadines",
  "156": "Azerbaijan",
  "157": "Mongolia",
  "158": "Syria",
  "159": "England",
  "160": "Marshall Islands",
  "162": "Scotland",
  "163": "Spain",
  "164": "United Kingdom",
  "166": "Wales",
  "175": "South Korea",
  "176": "Kyrgyzstan",
  "177": "Bangladesh",
  "178": "Sudan",
  "179": "Benin",
  "180": "Bhutan",
  "181": "Botswana",
  "182": "Brunei",
  "183": "Burundi",
  "184": "Cambodia",
  "185": "Cameroon",
  "186": "Cape Verde",
  "187": "Central Africa",
  "188": "Chad",
  "189": "Congo",
  "190": "Ivory Coast",
  "191": "Djibouti",
  "192": "Equatorial Guinea",
  "193": "Gabon",
  "194": "Ghana",
  "195": "Kenya",
  "196": "Laos",
  "197": "Liberia",
  "198": "Madagascar",
  "199": "Morocco",
  "200": "Mozambique",
  "201": "Myanmar",
  "202": "Namibia",
  "203": "Niger",
  "204": "Nigeria",
  "206": "Qatar",
  "207": "Rwanda",
  "208": "Samoa",
  "209": "Sao Tome/Principe",
  "210": "Senegal",
  "211": "Sierra Leone",
  "212": "Somalia",
  "213": "Sri Lanka",
  "214": "Eswatini",
  "215": "Tajikistan",
  "216": "Tanzania",
  "217": "Timor-Leste",
  "218": "Togo",
  "219": "Tunisia",
  "220": "Uganda",
  "221": "Zambia",
  "222": "Zimbabwe",
  "223": "Algeria",
  "224": "Mauritania",
  "225": "International",
  "231": "Serbia",
  "241": "Montenegro",
  "261": "Libya",
  "271": "The Gambia",
  "281": "Malawi",
  "291": "Palestine",
  "301": "Ethiopia",
  "311": "Mauritius",
  "312": "Lesotho",
  "313": "Mali",
  "314": "Maldives",
  "318": "DR Congo",
  "319": "Angola",
  "320": "Comoros",
  "321": "Eritrea",
  "322": "Guinea",
  "323": "Guinea-Bissau",
  "324": "Micronesia",
  "325": "North Korea",
  "326": "Palau",
  "327": "Seychelles",
  "328": "Western Sahara",
  "329": "British Virgin Islands",
  "330": "South Sudan",
  "334": "Burkina Faso",
  "339": "Sint Maarten",
  "340": "Turks and Caicos Islands",
  "350": "French Polynesia",
};

// ---- LIVE-GAME path -------------------------------------------------------------------------------
// Archive/history pages tag nationality with the opaque numeric id (country-2). LIVE game pages use
// the ISO/pseudo country CODE instead (country-us, country-dk, country-xe). Same source of truth
// (flag_map.csv) keyed by that code (uppercased) so both DOM shapes resolve to the same art.
export const COUNTRY_CODE_TO_FLAG = {
  "US": "US",
  "CA": "CA",
  "AR": "AR",
  "BE": "BE",
  "AF": "AF",
  "AL": "AL",
  "AD": "AD",
  "AI": "AI",
  "AG": "AG",
  "AM": "AM",
  "AW": "AW",
  "AU": "AU",
  "AT": "AT",
  "BS": "BS",
  "BH": "BH",
  "BB": "BB",
  "BY": "BY",
  "BZ": "BZ",
  "BM": "BM",
  "BO": "BO",
  "BA": "BA",
  "BR": "BR",
  "BG": "BG",
  "KY": "KY",
  "CL": "CL",
  "CN": "CN",
  "CO": "CO",
  "CR": "CR",
  "HR": "HR",
  "CU": "CU",
  "CW": "CW",
  "CY": "CY",
  "CZ": "CZ",
  "DK": "DK",
  "DM": "DM",
  "DO": "DO",
  "EC": "EC",
  "EG": "EG",
  "SV": "SV",
  "EE": "EE",
  "FO": "FO",
  "FJ": "FJ",
  "FI": "FI",
  "FR": "FR",
  "GE": "GE",
  "DE": "DE",
  "GI": "GI",
  "GR": "GR",
  "GL": "GL",
  "GD": "GD",
  "GU": "GU",
  "GT": "GT",
  "GY": "GY",
  "HT": "HT",
  "HN": "HN",
  "HK": "HK",
  "HU": "HU",
  "IS": "IS",
  "IN": "IN",
  "ID": "ID",
  "IR": "IR",
  "IQ": "IQ",
  "IE": "IE",
  "IM": "IM",
  "IL": "IL",
  "IT": "IT",
  "JM": "JM",
  "JP": "JP",
  "JO": "JO",
  "KZ": "KZ",
  "KI": "KI",
  "KW": "KW",
  "LV": "LV",
  "LB": "LB",
  "LI": "LI",
  "LT": "LT",
  "LU": "LU",
  "MO": "MO",
  "MK": "MK",
  "MY": "MY",
  "MT": "MT",
  "MX": "MX",
  "MD": "MD",
  "MC": "MC",
  "MS": "MS",
  "NR": "NR",
  "NP": "NP",
  "NL": "NL",
  "NZ": "NZ",
  "NI": "NI",
  "NO": "NO",
  "OM": "OM",
  "PK": "PK",
  "PA": "PA",
  "PG": "PG",
  "PY": "PY",
  "PE": "PE",
  "PH": "PH",
  "PL": "PL",
  "PT": "PT",
  "PR": "PR",
  "RO": "RO",
  "RU": "RU",
  "KN": "KN",
  "LC": "LC",
  "SM": "SM",
  "SA": "SA",
  "SG": "SG",
  "SK": "SK",
  "SI": "SI",
  "SB": "SB",
  "ZA": "ZA",
  "SR": "SR",
  "SE": "SE",
  "CH": "CH",
  "TW": "TW",
  "TH": "TH",
  "TO": "TO",
  "TT": "TT",
  "TR": "TR",
  "TM": "TM",
  "TV": "TV",
  "UA": "UA",
  "AE": "AE",
  "UY": "UY",
  "UZ": "UZ",
  "VU": "VU",
  "VA": "VA",
  "VE": "VE",
  "VN": "VN",
  "YE": "YE",
  "AS": "AS",
  "VC": "VC",
  "AZ": "AZ",
  "MN": "MN",
  "SY": "SY",
  "XE": "GB_ENG",
  "MH": "MH",
  "XS": "GB_SCT",
  "ES": "ES",
  "GB": "GB",
  "XW": "GB_WLS",
  "KR": "KR",
  "KG": "KG",
  "BD": "BD",
  "SD": "SD",
  "BJ": "BJ",
  "BT": "BT",
  "BW": "BW",
  "BN": "BN",
  "BI": "BI",
  "KH": "KH",
  "CM": "CM",
  "CV": "CV",
  "CF": "CF",
  "TD": "TD",
  "CG": "CG",
  "CI": "CI",
  "DJ": "DJ",
  "GQ": "GQ",
  "GA": "GA",
  "GH": "GH",
  "KE": "KE",
  "LA": "LA",
  "LR": "LR",
  "MG": "MG",
  "MA": "MA",
  "MZ": "MZ",
  "MM": "MM",
  "NA": "NA",
  "NE": "NE",
  "NG": "NG",
  "QA": "QA",
  "RW": "RW",
  "WS": "WS",
  "ST": "ST",
  "SN": "SN",
  "SL": "SL",
  "SO": "SO",
  "LK": "LK",
  "SZ": "SZ",
  "TJ": "TJ",
  "TZ": "TZ",
  "TL": "TL",
  "TG": "TG",
  "TN": "TN",
  "UG": "UG",
  "ZM": "ZM",
  "ZW": "ZW",
  "DZ": "DZ",
  "MR": "MR",
  "XX": "UN",
  "RS": "RS",
  "ME": "ME",
  "LY": "LY",
  "GM": "GM",
  "MW": "MW",
  "PS": "PS",
  "ET": "ET",
  "MU": "MU",
  "LS": "LS",
  "ML": "ML",
  "MV": "MV",
  "CD": "CD",
  "AO": "AO",
  "KM": "KM",
  "ER": "ER",
  "GN": "GN",
  "GW": "GW",
  "FM": "FM",
  "KP": "KP",
  "PW": "PW",
  "SC": "SC",
  "EH": "EH",
  "VG": "VG",
  "SS": "SS",
  "BF": "BF",
  "SX": "SX",
  "TC": "TC",
  "PF": "PF",
};
export const COUNTRY_CODE_TO_NAME = {
  "US": "United States",
  "CA": "Canada",
  "AR": "Argentina",
  "BE": "Belgium",
  "AF": "Afghanistan",
  "AL": "Albania",
  "AD": "Andorra",
  "AI": "Anguilla",
  "AG": "Antigua/Barbuda",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BB": "Barbados",
  "BY": "Belarus",
  "BZ": "Belize",
  "BM": "Bermuda",
  "BO": "Bolivia",
  "BA": "Bosnia-Herzegovina",
  "BR": "Brazil",
  "BG": "Bulgaria",
  "KY": "Cayman Islands",
  "CL": "Chile",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "HR": "Croatia",
  "CU": "Cuba",
  "CW": "Curacao",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "EE": "Estonia",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GE": "Georgia",
  "DE": "Germany",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GU": "Guam",
  "GT": "Guatemala",
  "GY": "Guyana",
  "HT": "Haiti",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Isle of Man",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KI": "Kiribati",
  "KW": "Kuwait",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macao",
  "MK": "North Macedonia",
  "MY": "Malaysia",
  "MT": "Malta",
  "MX": "Mexico",
  "MD": "Moldova",
  "MC": "Monaco",
  "MS": "Montserrat",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "RO": "Romania",
  "RU": "Russia",
  "KN": "Saint Kitts/Nevis",
  "LC": "Saint Lucia",
  "SM": "San Marino",
  "SA": "Saudi Arabia",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "ZA": "South Africa",
  "SR": "Suriname",
  "SE": "Sweden",
  "CH": "Switzerland",
  "TW": "Taiwan",
  "TH": "Thailand",
  "TO": "Tonga",
  "TT": "Trinidad/Tobago",
  "TR": "Türkiye",
  "TM": "Turkmenistan",
  "TV": "Tuvalu",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatican City",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "YE": "Yemen",
  "AS": "American Samoa",
  "VC": "Saint Vincent and the Grenadines",
  "AZ": "Azerbaijan",
  "MN": "Mongolia",
  "SY": "Syria",
  "XE": "England",
  "MH": "Marshall Islands",
  "XS": "Scotland",
  "ES": "Spain",
  "GB": "United Kingdom",
  "XW": "Wales",
  "KR": "South Korea",
  "KG": "Kyrgyzstan",
  "BD": "Bangladesh",
  "SD": "Sudan",
  "BJ": "Benin",
  "BT": "Bhutan",
  "BW": "Botswana",
  "BN": "Brunei",
  "BI": "Burundi",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CV": "Cape Verde",
  "CF": "Central Africa",
  "TD": "Chad",
  "CG": "Congo",
  "CI": "Ivory Coast",
  "DJ": "Djibouti",
  "GQ": "Equatorial Guinea",
  "GA": "Gabon",
  "GH": "Ghana",
  "KE": "Kenya",
  "LA": "Laos",
  "LR": "Liberia",
  "MG": "Madagascar",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NE": "Niger",
  "NG": "Nigeria",
  "QA": "Qatar",
  "RW": "Rwanda",
  "WS": "Samoa",
  "ST": "Sao Tome/Principe",
  "SN": "Senegal",
  "SL": "Sierra Leone",
  "SO": "Somalia",
  "LK": "Sri Lanka",
  "SZ": "Eswatini",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TN": "Tunisia",
  "UG": "Uganda",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "DZ": "Algeria",
  "MR": "Mauritania",
  "XX": "International",
  "RS": "Serbia",
  "ME": "Montenegro",
  "LY": "Libya",
  "GM": "The Gambia",
  "MW": "Malawi",
  "PS": "Palestine",
  "ET": "Ethiopia",
  "MU": "Mauritius",
  "LS": "Lesotho",
  "ML": "Mali",
  "MV": "Maldives",
  "CD": "DR Congo",
  "AO": "Angola",
  "KM": "Comoros",
  "ER": "Eritrea",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "FM": "Micronesia",
  "KP": "North Korea",
  "PW": "Palau",
  "SC": "Seychelles",
  "EH": "Western Sahara",
  "VG": "British Virgin Islands",
  "SS": "South Sudan",
  "BF": "Burkina Faso",
  "SX": "Sint Maarten",
  "TC": "Turks and Caicos Islands",
  "PF": "French Polynesia",
};

// content.js scrapes whatever token follows `country-` in the player's flag class. That's a numeric
// id on archive/history pages (country-2) but an ISO/pseudo code on live game pages (country-us). We
// accept either: all-digits -> id table, otherwise -> code table (uppercased).
const isNumericToken = (t) => /^\d+$/.test(t);

/** Flag basename ("US", "GB_ENG") for a Chess.com country token (id or code), or null if no art. */
export function flagCodeForCountryId(token) {
  if (token == null) return null;
  const t = String(token).trim();
  if (!t) return null;
  return (isNumericToken(t) ? COUNTRY_ID_TO_FLAG[t] : COUNTRY_CODE_TO_FLAG[t.toUpperCase()]) || null;
}

/** Display name ("United States") for a Chess.com country token (id or code), or null if unknown. */
export function countryNameForId(token) {
  if (token == null) return null;
  const t = String(token).trim();
  if (!t) return null;
  return (isNumericToken(t) ? COUNTRY_ID_TO_NAME[t] : COUNTRY_CODE_TO_NAME[t.toUpperCase()]) || null;
}
