// Research-only all-legal root panels. Callers own guarded admission and a
// registered, frozen cohort/policy; this module does not select games or fit.
import {readFile,writeFile,appendFile,mkdir,stat} from 'node:fs/promises';
import {gzipSync} from 'node:zlib';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {Chess} from '../lib/chess.js';
import {Engine} from '../tools/calibration/engine.mjs';
import {sha256} from './data-policy.mjs';
import {queryKey,validateQuery} from './experiments/E012-offer-evidence/code/queries.mjs';
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export function validatePanel(raw,selected,games,policy,packId){
  if(raw.schema!=='research-root-panel-v1'||!raw.complete||raw.packId!==packId||raw.policySha256!==sha256(JSON.stringify(policy))||!same(raw.engineConfigs,policy.engineConfigs)||!same(raw.configHashes,policy.configHashes)||!same(raw.games,games)||raw.positions.length!==selected.length)throw Error('Changed/incomplete root panel');
  const queries=new Map(),used=new Set(),fens=new Map();for(const r of raw.searches){validateQuery(r);if(queries.has(r.key)||!Object.values(policy.configHashes).includes(r.configHash))throw Error('Unknown/duplicate root query');queries.set(r.key,r);}
  function score(key,c,mode,restricted){const r=queries.get(key);if(!r||key!==queryKey(policy.configHashes[mode],c.history,restricted)||!same(r.history,c.history)||r.configHash!==policy.configHashes[mode]||r.restricted!==restricted)throw Error('Changed history/budget/restriction');used.add(key);fens.set(key,c.move.before);return r.score;}
  const cases=selected.map((c,i)=>{const p=raw.positions[i],core=Object.fromEntries(Object.keys(c).map(k=>[k,p[k]]));if(!same(core,c)||!same(Object.keys(p).sort(),[...Object.keys(c),'keys'].sort()))throw Error('Changed root case');
    const scores=Object.fromEntries(['20k','80k'].map(mode=>{const k=p.keys[mode];if(!k||!same(k.alternatives.map(a=>a.move),c.legalMoves))throw Error('Incomplete legal alternatives');return[mode,{root:score(k.rootKey,c,mode,null),alternatives:k.alternatives.map(a=>({move:a.move,score:score(a.key,c,mode,a.move)})),playedIndex:c.legalMoves.indexOf(c.played)}];}));return{...c,scores};});
  if(used.size!==queries.size)throw Error('Unused injected query');for(const [key,r] of queries){const b=new Chess(fens.get(key));for(const m of r.pv.split(' '))b.move({from:m.slice(0,2),to:m.slice(2,4),promotion:m[4]});}
  return{cases,diagnostics:{cases:cases.length,uniqueGames:new Set(cases.map(c=>c.gameId)).size,uniqueQueries:queries.size,legalAlternatives:cases.reduce((n,c)=>n+c.legalMoves.length,0),budgets:Object.fromEntries(Object.entries(policy.configHashes).map(([mode,h])=>{const rs=raw.searches.filter(r=>r.configHash===h);return[mode,{queries:rs.length,earlierExactScores:rs.filter(r=>r.rawInfo!==r.finalSearchInfo).length,exactRecoveries:rs.filter(r=>r.exactRecovery).length,selectedNodes:[Math.min(...rs.map(r=>r.nodes)),Math.max(...rs.map(r=>r.nodes))],finalNodes:[Math.min(...rs.map(r=>r.finalNodes)),Math.max(...rs.map(r=>r.finalNodes))]}];}))}};
}
export async function collectPanel({root,id,selected,games,policy,packId,access,codeSha256,sharedCodeSha256,engineFile,out,command,maxRequests=3000,maxMs=900000,maxBytes=3*1024*1024}){
  const directory=path.join(root,'research/runs',id,'sf18'),cacheFile=path.join(directory,'searches.jsonl');try{await stat(cacheFile);throw Error('Unregistered partial cache; explicit provenance-checked recovery required');}catch(e){if(e.code!=='ENOENT')throw e;}
  await mkdir(directory,{recursive:true});const revision=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8',windowsHide:true}).trim(),policySha256=sha256(JSON.stringify(policy)),header={schema:'research-root-cache-v1',sourceRevision:revision,codeSha256,sharedCodeSha256,engineConfigs:policy.engineConfigs,configHashes:policy.configHashes,policySha256,packId,selectionHash:sha256(JSON.stringify(selected)),dataEligibility:access.receipt};
  await writeFile(path.join(directory,'header.json'),JSON.stringify(header,null,2)+'\n');const engine=new Engine(engineFile),cache=new Map(),positions=[],started=performance.now();let completed=0,requests=0,reused=0;
  async function progress(state,error){await writeFile(path.join(directory,'progress.json'),JSON.stringify({state,processId:process.pid,engineProcessId:engine.child.pid,sourceRevision:revision,completedCases:completed,totalCases:selected.length,queries:cache.size,requests,reused,elapsedMs:performance.now()-started,...(error?{error}:{})},null,2)+'\n');}
  async function search(c,mode,restricted){const h=policy.configHashes[mode],key=queryKey(h,c.history,restricted);if(cache.has(key)){reused++;return key;}if(requests+2>maxRequests||performance.now()-started>maxMs)throw Error('Compute cap exceeded');
    const r=await engine.search(c.history,restricted,policy.engineConfigs[mode].budget);requests+=r.exactRecovery?2:1;const row={key,configHash:h,history:c.history,restricted,...r,finalNodes:Number(/\bnodes (\d+)/.exec(r.finalSearchInfo)?.[1])};validateQuery(row);cache.set(key,row);await appendFile(cacheFile,JSON.stringify(row)+'\n');return key;}
  try{const startup=await engine.init(policy.engineConfigs['20k']);await progress('running');for(const c of selected){const keys={};for(const mode of ['20k','80k']){const rootKey=await search(c,mode,null),alternatives=[];for(const move of c.legalMoves)alternatives.push({move,key:await search(c,mode,move)});keys[mode]={rootKey,alternatives};}positions.push({...c,keys});completed++;await progress('running');console.log(completed+'/'+selected.length+' cases; '+cache.size+' queries; '+Math.round((performance.now()-started)/1000)+' seconds');}
    const raw={schema:'research-root-panel-v1',complete:true,packId,policySha256,engineConfigs:policy.engineConfigs,configHashes:policy.configHashes,games,positions,searches:[...cache.values()]},bytes=gzipSync(JSON.stringify(raw)+'\n');if(bytes.length>maxBytes)throw Error('Retained evidence cap exceeded');await mkdir(out,{recursive:true});await writeFile(path.join(out,'sf18-observations.json.gz'),bytes);
    await writeFile(path.join(out,'collection-run.json'),JSON.stringify({...header,schema:'research-run-v1',id:id+'-all-root-collection',date:'2026-10-05',command,environment:{node:process.version,platform:process.platform,arch:process.arch},startupIdentity:startup.identity,cases:selected.length,queries:cache.size,requests,reused,elapsedMs:performance.now()-started,modelFits:0,propertyAssessments:0,humanLabelsUsed:0,outputs:{'sf18-observations.json.gz':sha256(bytes)}},null,2)+'\n');await progress('completed');console.log(JSON.stringify({complete:true,cases:selected.length,queries:cache.size,requests,reused,bytes:bytes.length,propertyAssessments:0}));
  }catch(e){await progress('failed',e.message);throw e;}finally{engine.close();}
}
export async function sharedHashes(root,files){const values=await Promise.all(files.map(async name=>[name,sha256(await readFile(path.join(root,name)))]));return Object.fromEntries(values);}
